title: Craig Asberry, PhD
logo: "/images/CRAIG_Headshot.jpg?raw=true"
description: Data Scientist and Analyst with a passion for clearly answering complex questions. 
      My skills in social science methods and machine learning as well as subject matter expertise 
      in communication, public policy, healthcare, and governmental processes allow me to answer
      impactful questions leading to enhanced efficiency.
  
  <a href="https://www.linkedin.com/in/craig-asberry-25322588/"> 
  View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
